config/routes.rb
Pareto::Application.routes.draw do
  resources :workflows

  resources :patients

  resources :dd_fk_values

  resources :dd_fk_columns

  resources :dd_string_values

  resources :dd_tables do
    resources :dd_rows, :except => [:index]
    resources :dd_string_columns
  end

  root :to => 'pages#home'

end

app/models/dd_string_value.rb
class DdStringValue < ActiveRecord::Base
  belongs_to :dd_row
  belongs_to :dd_string_column
end

app/controllers/dd_string_values_controller.rb
class DdStringValuesController < ApplicationController
  # GET /dd_string_values
  # GET /dd_string_values.xml
  def index
    @dd_string_values = DdStringValue.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @dd_string_values }
    end
  end

  # GET /dd_string_values/1
  # GET /dd_string_values/1.xml
  def show
    @dd_string_value = DdStringValue.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @dd_string_value }
    end
  end

  # GET /dd_string_values/new
  # GET /dd_string_values/new.xml
  def new
    @dd_string_value = DdStringValue.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @dd_string_value }
    end
  end

  # GET /dd_string_values/1/edit
  def edit
    @dd_string_value = DdStringValue.find(params[:id])
  end

  # POST /dd_string_values
  # POST /dd_string_values.xml
  def create
    @dd_string_value = DdStringValue.new(params[:dd_string_value])

    respond_to do |format|
      if @dd_string_value.save
        format.html { redirect_to(@dd_string_value, :notice => 'Dd string value was successfully created.') }
        format.xml  { render :xml => @dd_string_value, :status => :created, :location => @dd_string_value }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @dd_string_value.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /dd_string_values/1
  # PUT /dd_string_values/1.xml
  def update
    @dd_string_value = DdStringValue.find(params[:id])

    respond_to do |format|
      if @dd_string_value.update_attributes(params[:dd_string_value])
        format.html { redirect_to(@dd_string_value, :notice => 'Dd string value was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @dd_string_value.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /dd_string_values/1
  # DELETE /dd_string_values/1.xml
  def destroy
    @dd_string_value = DdStringValue.find(params[:id])
    @dd_string_value.destroy

    respond_to do |format|
      format.html { redirect_to(dd_string_values_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/dd_string_values_helper.rb
module DdStringValuesHelper
end

app/views/dd_string_values/_form.html.erb
<%= form_for(@dd_string_value) do |f| %>
  <% if @dd_string_value.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dd_string_value.errors.count, "error") %> prohibited this dd_string_value from being saved:</h2>

      <ul>
      <% @dd_string_value.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dd_row_id %><br />
    <%= f.text_field :dd_row_id %>
  </div>
  <div class="field">
    <%= f.label :dd_string_column_id %><br />
    <%= f.text_field :dd_string_column_id %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dd_string_values/edit.html.erb
<h1>Editing dd_string_value</h1>

<%= render 'form' %>

<%= link_to 'Show', @dd_string_value %> |
<%= link_to 'Back', dd_string_values_path %>

app/views/dd_string_values/index.html.erb
<h1>Listing dd_string_values</h1>

<table>
  <tr>
    <th>Dd row</th>
    <th>Dd string column</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dd_string_values.each do |dd_string_value| %>
  <tr>
    <td><%= dd_string_value.dd_row_id %></td>
    <td><%= dd_string_value.dd_string_column_id %></td>
    <td><%= dd_string_value.value %></td>
    <td><%= link_to 'Show', dd_string_value %></td>
    <td><%= link_to 'Edit', edit_dd_string_value_path(dd_string_value) %></td>
    <td><%= link_to 'Destroy', dd_string_value, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dd string value', new_dd_string_value_path %>

app/views/dd_string_values/new.html.erb
<h1>New dd_string_value</h1>

<%= render 'form' %>

<%= link_to 'Back', dd_string_values_path %>

app/views/dd_string_values/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Dd row:</b>
  <%= @dd_string_value.dd_row_id %>
</p>

<p>
  <b>Dd string column:</b>
  <%= @dd_string_value.dd_string_column_id %>
</p>

<p>
  <b>Value:</b>
  <%= @dd_string_value.value %>
</p>


<%= link_to 'Edit', edit_dd_string_value_path(@dd_string_value) %> |
<%= link_to 'Back', dd_string_values_path %>