config/routes.rb
Pareto::Application.routes.draw do
  resources :workflows

  resources :patients

  resources :dd_fk_values

  resources :dd_fk_columns

  resources :dd_string_values

  resources :dd_tables do
    resources :dd_rows, :except => [:index]
    resources :dd_string_columns
  end

  root :to => 'pages#home'

end

app/models/dd_string_column.rb
class DdStringColumn < ActiveRecord::Base
  belongs_to :dd_table
  has_many :dd_string_value
end

app/controllers/dd_string_columns_controller.rb
class DdStringColumnsController < ApplicationController
  # GET /dd_string_columns
  # GET /dd_string_columns.xml
  def index
    @dd_string_columns = DdStringColumn.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @dd_string_columns }
    end
  end

  # GET /dd_string_columns/1
  # GET /dd_string_columns/1.xml
  def show
    @dd_string_column = DdStringColumn.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @dd_string_column }
    end
  end

  # GET /dd_string_columns/new
  # GET /dd_string_columns/new.xml
  def new
    @dd_table = DdTable.find(params[:dd_table_id])
    @dd_string_column = DdStringColumn.new
    @dd_string_column.dd_table_id = @dd_table.id
    @the_url = dd_table_dd_string_columns_path(@dd_table)
    @submit_text = "Create"

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @dd_string_column }
    end
  end

  # GET /dd_string_columns/1/edit
  def edit
    @dd_string_column = DdStringColumn.find(params[:id])
    @dd_tables = DdTable.all
  end

  # POST /dd_string_columns
  # POST /dd_string_columns.xml
  def create
    @dd_table = DdTable.find(params[:dd_table_id])
    @dd_string_column = DdStringColumn.new(params[:dd_string_column])

    respond_to do |format|
      if @dd_string_column.save
        format.html { redirect_to(@dd_table, :notice => 'Column was successfully created.') }
        format.xml  { render :xml => @dd_string_column, :status => :created, :location => @dd_string_column }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @dd_string_column.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /dd_string_columns/1
  # PUT /dd_string_columns/1.xml
  def update
    @dd_string_column = DdStringColumn.find(params[:id])

    respond_to do |format|
      if @dd_string_column.update_attributes(params[:dd_string_column])
        format.html { redirect_to(@dd_string_column, :notice => 'Dd string column was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @dd_string_column.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /dd_string_columns/1
  # DELETE /dd_string_columns/1.xml
  def destroy
    @dd_string_column = DdStringColumn.find(params[:id])
    @dd_string_column.destroy

    respond_to do |format|
      format.html { redirect_to(dd_string_columns_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/dd_string_columns_helper.rb
module DdStringColumnsHelper
end

app/views/dd_string_columns/_form.html.erb
<%= form_for(@dd_string_column, :url => @the_url) do |f| %>
  <% if @dd_string_column.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dd_string_column.errors.count, "error") %> prohibited this dd_string_column from being saved:</h2>

      <ul>
      <% @dd_string_column.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <%= f.hidden_field :dd_table_id %>
  <div class="actions">
    <%= f.submit @submit_text %>
  </div>
<% end %>

app/views/dd_string_columns/edit.html.erb
<h1>Editing dd_string_column</h1>

<%= render 'form' %>

<%= link_to 'Show', @dd_string_column %> |
<%= link_to 'Back', dd_string_columns_path %>

app/views/dd_string_columns/index.html.erb
<h1>Listing dd_string_columns</h1>

<table>
  <tr>
    <th>Dd table</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dd_string_columns.each do |dd_string_column| %>
  <tr>
    <td><%= dd_string_column.dd_table.name %></td>
    <td><%= dd_string_column.name %></td>
    <td><%= link_to 'Show', dd_string_column %></td>
    <td><%= link_to 'Edit', edit_dd_string_column_path(dd_string_column) %></td>
    <td><%= link_to 'Destroy', dd_string_column, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dd string column', new_dd_string_column_path %>

app/views/dd_string_columns/new.html.erb
<div>
  Create a Column for <%= @dd_table.name %>
</div>

<%= render 'form' %>

<%= link_to 'Back to ' + @dd_table.name, @dd_table %>

app/views/dd_string_columns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Dd table:</b>
  <%= @dd_string_column.dd_table_id %>
</p>

<p>
  <b>Name:</b>
  <%= @dd_string_column.name %>
</p>


<%= link_to 'Edit', edit_dd_string_column_path(@dd_string_column) %> |
<%= link_to 'Back', dd_string_columns_path %>