config/routes.rb
Pareto::Application.routes.draw do
  resources :workflows

  resources :patients

  resources :dd_fk_values

  resources :dd_fk_columns

  resources :dd_string_values

  resources :dd_tables do
    resources :dd_rows, :except => [:index]
    resources :dd_string_columns
  end

  root :to => 'pages#home'

end

app/controllers/dd_tables_controller.rb
class DdTablesController < ApplicationController
  # GET /dd_tables
  # GET /dd_tables.xml
  def index
    @dd_tables = DdTable.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @dd_tables }
    end
  end

  # GET /dd_tables/1
  # GET /dd_tables/1.xml
  def show
    @dd_table = DdTable.find(params[:id])
    build_table_data

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @dd_table }
    end
  end


  # GET /dd_tables/new
  # GET /dd_tables/new.xml
  def new
    @submit_text = "Create"
    @dd_table = DdTable.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @dd_table }
    end
  end

  # GET /dd_tables/1/edit
  def edit
    @dd_table = DdTable.find(params[:id])
  end

  # POST /dd_tables
  # POST /dd_tables.xml
  def create
    @dd_table = DdTable.new(params[:dd_table])

    respond_to do |format|
      if @dd_table.save
        format.html { redirect_to(@dd_table, :notice => 'Dd table was successfully created.') }
        format.xml  { render :xml => @dd_table, :status => :created, :location => @dd_table }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @dd_table.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /dd_tables/1
  # PUT /dd_tables/1.xml
  def update
    @submit_text = "Update"
    @dd_table = DdTable.find(params[:id])

    respond_to do |format|
      if @dd_table.update_attributes(params[:dd_table])
        format.html { redirect_to(@dd_table, :notice => 'Dd table was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @dd_table.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /dd_tables/1
  # DELETE /dd_tables/1.xml
  def destroy
    @dd_table = DdTable.find(params[:id])
    @dd_table.destroy

    respond_to do |format|
      format.html { redirect_to(dd_tables_url) }
      format.xml  { head :ok }
    end
  end

  private

    def build_table_data
      @columns = @dd_table.dd_string_columns
      column_id_to_index = map_id_to_index(@columns)

      rows = @dd_table.dd_rows
      row_id_to_index = map_id_to_index(rows)

      @table_data = Array.new(rows.length) { Array.new(@columns.length) }

      rows.each do |row|
        i = row_id_to_index[row.id]
        row.dd_string_values.each do |value|
          j = column_id_to_index[value.dd_string_column_id]
          @table_data[i][j] = value
        end
      end
    end

    def map_id_to_index(array)
      id_to_index = {}
      array.each_index do |i|
        id_to_index[array[i].id] = i
      end
      id_to_index
    end

end

app/helpers/dd_tables_helper.rb
module DdTablesHelper
end

app/views/dd_tables/_form.html.erb
<%= form_for(@dd_table) do |f| %>
  <% if @dd_table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dd_table.errors.count, "error") %> prohibited this dd_table from being saved:</h2>

      <ul>
      <% @dd_table.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit @submit_text %>
  </div>
<% end %>

app/views/dd_tables/_table_view.html.erb
<table>
  <tr>
    <% @columns.each do |column| %>
      <th><%= column.name %></th>
    <% end %>
    <th></th>
  </tr>
  <% @table_data.each do |row| %>
    <tr>
      <% row.each do |col| %>
        <td><%= col.value unless col.blank? %>&nbsp;</td>
      <% end %>
      <td>
        <%= link_to 'Edit', edit_dd_table_dd_row_path(@dd_table, row.first.dd_row_id) %>
        <%= link_to 'Destroy', dd_table_dd_row_path(@dd_table, row.first.dd_row_id), :method => :delete %>
      </td>
    </tr>
  <% end %>
</table>

app/views/dd_tables/edit.html.erb
<div>
  Edit <%= @dd_table.name %>
</div>

<div>
  <%= render 'form' %>
</div>

<div>
  <%= link_to 'Back to ' + @dd_table.name, @dd_table %>
</div>

app/views/dd_tables/index.html.erb
<div>
  Tables
</div>

<div>
  <ul>
    <% @dd_tables.each do |dd_table| %>
      <li><%= link_to dd_table.name, dd_table %>
    <% end %>
  </ul>
</div>

<%= link_to 'Create a Table', new_dd_table_path %>

app/views/dd_tables/new.html.erb
<h1>Create a Table</h1>

<%= render 'form' %>

<%= link_to 'Back', dd_tables_path %>

app/views/dd_tables/show.html.erb
<p id="notice"><%= notice %></p>

<div>
  <div>
    <%= @dd_table.name %>
  </div>
  <div>
    <%= link_to "Edit", edit_dd_table_path(@dd_table) %>
  </div>
  <div>
    <%= link_to "Create a column", new_dd_table_dd_string_column_path(@dd_table) %>
  </div>
</div>

<% create_link = link_to 'Create a row', new_dd_table_dd_row_path(@dd_table) %>

<div>
  <%= create_link %>
</div>

<div>
  <%= render 'table_view' %>
</div>

<div>
  <%= create_link %>
</div>