config/routes.rb
Pareto::Application.routes.draw do
  resources :workflows

  resources :patients

  resources :dd_fk_values

  resources :dd_fk_columns

  resources :dd_string_values

  resources :dd_tables do
    resources :dd_rows, :except => [:index]
    resources :dd_string_columns
  end

  root :to => 'pages#home'

end

app/models/dd_fk_value.rb
class DdFkValue < ActiveRecord::Base
  belongs_to :dd_row
  belongs_to :dd_fk_column
end

app/controllers/dd_fk_values_controller.rb
class DdFkValuesController < ApplicationController
  # GET /dd_fk_values
  # GET /dd_fk_values.xml
  def index
    @dd_fk_values = DdFkValue.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @dd_fk_values }
    end
  end

  # GET /dd_fk_values/1
  # GET /dd_fk_values/1.xml
  def show
    @dd_fk_value = DdFkValue.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @dd_fk_value }
    end
  end

  # GET /dd_fk_values/new
  # GET /dd_fk_values/new.xml
  def new
    @dd_fk_value = DdFkValue.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @dd_fk_value }
    end
  end

  # GET /dd_fk_values/1/edit
  def edit
    @dd_fk_value = DdFkValue.find(params[:id])
  end

  # POST /dd_fk_values
  # POST /dd_fk_values.xml
  def create
    @dd_fk_value = DdFkValue.new(params[:dd_fk_value])

    respond_to do |format|
      if @dd_fk_value.save
        format.html { redirect_to(@dd_fk_value, :notice => 'Dd fk value was successfully created.') }
        format.xml  { render :xml => @dd_fk_value, :status => :created, :location => @dd_fk_value }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @dd_fk_value.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /dd_fk_values/1
  # PUT /dd_fk_values/1.xml
  def update
    @dd_fk_value = DdFkValue.find(params[:id])

    respond_to do |format|
      if @dd_fk_value.update_attributes(params[:dd_fk_value])
        format.html { redirect_to(@dd_fk_value, :notice => 'Dd fk value was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @dd_fk_value.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /dd_fk_values/1
  # DELETE /dd_fk_values/1.xml
  def destroy
    @dd_fk_value = DdFkValue.find(params[:id])
    @dd_fk_value.destroy

    respond_to do |format|
      format.html { redirect_to(dd_fk_values_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/dd_fk_values_helper.rb
module DdFkValuesHelper
end

app/views/dd_fk_values/_form.html.erb
<%= form_for(@dd_fk_value) do |f| %>
  <% if @dd_fk_value.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dd_fk_value.errors.count, "error") %> prohibited this dd_fk_value from being saved:</h2>

      <ul>
      <% @dd_fk_value.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dd_row_id %><br />
    <%= f.text_field :dd_row_id %>
  </div>
  <div class="field">
    <%= f.label :dd_fk_column_id %><br />
    <%= f.text_field :dd_fk_column_id %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dd_fk_values/edit.html.erb
<h1>Editing dd_fk_value</h1>

<%= render 'form' %>

<%= link_to 'Show', @dd_fk_value %> |
<%= link_to 'Back', dd_fk_values_path %>

app/views/dd_fk_values/index.html.erb
<h1>Listing dd_fk_values</h1>

<table>
  <tr>
    <th>Dd row</th>
    <th>Dd fk column</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dd_fk_values.each do |dd_fk_value| %>
  <tr>
    <td><%= dd_fk_value.dd_row_id %></td>
    <td><%= dd_fk_value.dd_fk_column_id %></td>
    <td><%= dd_fk_value.value %></td>
    <td><%= link_to 'Show', dd_fk_value %></td>
    <td><%= link_to 'Edit', edit_dd_fk_value_path(dd_fk_value) %></td>
    <td><%= link_to 'Destroy', dd_fk_value, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dd fk value', new_dd_fk_value_path %>

app/views/dd_fk_values/new.html.erb
<h1>New dd_fk_value</h1>

<%= render 'form' %>

<%= link_to 'Back', dd_fk_values_path %>

app/views/dd_fk_values/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Dd row:</b>
  <%= @dd_fk_value.dd_row_id %>
</p>

<p>
  <b>Dd fk column:</b>
  <%= @dd_fk_value.dd_fk_column_id %>
</p>

<p>
  <b>Value:</b>
  <%= @dd_fk_value.value %>
</p>


<%= link_to 'Edit', edit_dd_fk_value_path(@dd_fk_value) %> |
<%= link_to 'Back', dd_fk_values_path %>